//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trading.StateMachine.BusinessLogic.Managers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trading.StateMachine.BusinessLogic.Managers.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ переданного типа для лота {0} уже существует.
        /// </summary>
        public static string LotDocumentService_Create_Документ_переданного_типа_для_лота__0__уже_существует {
            get {
                return ResourceManager.GetString("LotDocumentService_Create_Документ_переданного_типа_для_лота__0__уже_существует", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя лота не передано.
        /// </summary>
        public static string LotDocumentService_CreateAsync_Имя_лота_не_передано {
            get {
                return ResourceManager.GetString("LotDocumentService_CreateAsync_Имя_лота_не_передано", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название процедуры по коду {0} не найдено.
        /// </summary>
        public static string LotManager_ValidateAsync_Название_процедуры_по_коду__0__не_найдено {
            get {
                return ResourceManager.GetString("LotManager_ValidateAsync_Название_процедуры_по_коду__0__не_найдено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнен идентификатор организации.
        /// </summary>
        public static string Validate_Не_заполнен_идентификатор_организации {
            get {
                return ResourceManager.GetString("Validate_Не_заполнен_идентификатор_организации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заполнен идентификатор пользователя.
        /// </summary>
        public static string Validate_Не_заполнен_идентификатор_пользователя {
            get {
                return ResourceManager.GetString("Validate_Не_заполнен_идентификатор_пользователя", resourceCulture);
            }
        }
    }
}
